---
- name: deployment playbook
  hosts: all
  tasks:
    - name: deploy SSH keys to remote hosts
      include: plays/deploy_ssh.yml
    - name: copy example
      include_tasks: plays/copy_example.yml
